//! P7.5 — H_4 (icosahedral) sub-Coxeter projector for the gateway test.
//!
//! Companion to [`crate::route34::z3xz3_projector`] and
//! [`crate::route34::metric_laplacian_projected`]. Where those modules
//! project a bigraded test-function basis onto the trivial irrep of the
//! discrete Z/3 (Tian-Yau) or Z/3 × Z/3 (Schoen) symmetry, this module
//! adds an *additional* sub-Coxeter projection onto a subspace
//! identified with the **H_4 (icosahedral) Coxeter sub-group of E_8**.
//!
//! ## Why
//!
//! The journal §L.1 / §L.2 identifies the gateway eigenvalue ω_fix =
//! 1 − 1/dim(E_8) = 123/248 not with the lowest mode of the *full*
//! metric Laplacian, but with the lowest mode within the H_4 lepton
//! sector of E_8. The full bigraded-monomial basis used in
//! [`crate::route34::metric_laplacian`] mixes all sub-Coxeter sectors
//! (H_4 leptons + D_8 quarks + the other E_8 root strata), and P7.1 /
//! P7.1b / P7.2b found no eigenvalue near ω_fix in the resulting
//! spectrum. Hypothesis (3) of the falsification triangle: the basis
//! is the wrong rep — restrict to H_4 first, *then* solve.
//!
//! ## Group-theoretic background (Slansky 1981; Coxeter 1973;
//!    Conway-Sloane 1999 §4)
//!
//! E_8 has Coxeter number `h = 30` and exponents
//! `{1, 7, 11, 13, 17, 19, 23, 29}` — the eight integers in
//! `{1, …, 29}` coprime to 30. These are exactly the exponents of the
//! H_4 (icosahedral) Coxeter group, which is a Coxeter sub-group of
//! E_8 (this is the classical "icosian" embedding of Wilson 2009;
//! Conway-Sloane §4 §8.2). On the McKay-graph side of the (2, 3, 5)
//! triangle, the binary icosahedral group `2I` (order 120) maps to
//! the affine `Ê_8` Dynkin graph; on the Coxeter side, the H_4
//! Coxeter graph is the 4-node `5—3—3` chain whose Weyl group has
//! order 14400 = `120²`.
//!
//! The minimal **non-trivial** unitary representation of the
//! icosahedral rotation group `A_5` (order 60) on the bicubic
//! coordinates `(x_0:x_1:x_2)` (or `(y_0:y_1:y_2)`) is generated by
//! the diagonal fivefold rotation
//!
//! ```text
//!     R_5 : (x_0, x_1, x_2)  →  (x_0, ζ_5 x_1, ζ_5² x_2),
//! ```
//!
//! where `ζ_5 = exp(2π i / 5)`. This is consistent with the standard
//! Klein-Tonelli embedding of the dodecahedron into `CP^2` via
//! homogeneous coordinates with `Z_5`-weighted phases. (Klein 1884
//! "Vorlesungen über das Ikosaeder"; Du-Val 1964 "Homographies,
//! Quaternions, and Rotations" §8.) The same `R_5` is one of the four
//! `H_4` Coxeter generators acting on the simple roots — the others
//! are the 2-fold and 3-fold reflections that already overlap with
//! the Z/3 × Z/3 generators of the Schoen quotient.
//!
//! ## Action on Schoen monomials
//!
//! With the diagonal `R_5` realisation on both `(x_*)` and `(y_*)`
//! blocks (the Klein convention), the action on the Schoen
//! monomial-exponent tuple
//! `[a_0, a_1, a_2, b_0, b_1, b_2, c_0, c_1]` (encoding
//! `∏_k x_k^{a_k} ∏_k y_k^{b_k} t_0^{c_0} t_1^{c_1}`) is
//!
//! ```text
//!     χ_5(m) = (a_1 + 2 a_2 + b_1 + 2 b_2)  mod 5.
//! ```
//!
//! Note that this is **structurally the same formula** as the Z/3×Z/3
//! α-character, but reduced mod 5 instead of mod 3. The `t`-block
//! does not enter (the icosahedral fivefold acts as the identity on
//! the elliptic-fibre `(t_0:t_1)` direction in the Klein/Schoen
//! convention; one could instead take a fivefold rotation in `t` but
//! that would not commute with the Z/3 acting on `t_1` from
//! [`crate::route34::z3xz3_projector::beta_character`]).
//!
//! Combining with the existing Z/3 × Z/3 projection, the gateway
//! sector is the **(α, β, χ_5) = (0, 0, 0)** subset of basis monomials,
//! i.e. monomials simultaneously invariant under both the Schoen
//! Z/3 × Z/3 and the icosahedral Z/5 actions.
//!
//! ## Caveat
//!
//! This is the minimal **Z/5** of the full H_4 group — the
//! icosahedral fivefold rotation only. The complete H_4 Coxeter
//! action would also project on the 2-fold and 3-fold reflections;
//! those, however, partially overlap with the Z/3 × Z/3 generators
//! already projected against in [`crate::route34::z3xz3_projector`],
//! so the additional projection power gained from including them is
//! limited. The Z/5 projection alone is already a 1/5 reduction in
//! basis size (1/45 combined with Z/3 × Z/3 if independent), enough
//! to test whether ω_fix lives in this sector.
//!
//! ## Public surface
//!
//! Mirrors [`metric_laplacian_projected`]:
//!
//!   * [`icosa_z5_character`] — fivefold-character of a Schoen monomial.
//!   * [`build_h4_projected_basis_schoen`] — Schoen basis filter for
//!     `(α, β, χ_5) = (0, 0, 0)`.
//!   * [`compute_h4_projected_metric_laplacian_spectrum`] — Galerkin
//!     solve on the H_4-projected basis.
//!
//! ## P7.5 consumer
//!
//! [`crate::bin::p7_5_h4_gateway_test`] (binary) compares the lowest
//! H_4-projected eigenvalue to the ω_fix prediction.
//!
//! ## References
//!
//! * Coxeter, *Regular Polytopes*, 3rd ed. (Dover 1973), Tab. I (H_4
//!   Coxeter graph and exponents).
//! * Slansky, "Group Theory for Unified Model Building", *Phys. Rep.*
//!   **79** (1981) 1–128, §6 (E_8 root system and sub-Coxeter
//!   structure).
//! * Conway, Sloane, *Sphere Packings, Lattices and Groups*, 3rd ed.
//!   (Springer 1999), Ch. 4 §8.2 (icosian embedding into E_8).
//! * Wilson, R. A., *The Finite Simple Groups* (Springer 2009),
//!   §5.6.2 (icosahedral subgroup of E_8(2)).
//! * Klein, F., *Vorlesungen über das Ikosaeder* (Teubner 1884) —
//!   `Z_5` weights on `(x_0:x_1:x_2)`.
//! * Du Val, P., *Homographies, Quaternions, and Rotations*
//!   (Oxford 1964), §8 (binary icosahedral Z/5).

#![allow(clippy::needless_range_loop)]

use crate::route34::hym_hermitian::MetricBackground;
use crate::route34::metric_laplacian::{
    build_test_basis, MetricLaplacianConfig, MetricLaplacianSpectrum, TestMonomial,
};
use crate::route34::metric_laplacian_projected::{ty_z3_character, ProjectionKind};
use crate::route34::z3xz3_projector::{alpha_character, beta_character};
use num_complex::Complex64;
use serde::{Deserialize, Serialize};
use std::time::Instant;

/// Icosahedral fivefold-rotation character on Schoen monomials.
///
/// `χ_5(m) = (a_1 + 2 a_2 + b_1 + 2 b_2) mod 5`, with the same
/// `(0, 1, 2)` weight pattern on each `CP^2` block as the Z/3
/// α-character but reduced mod 5 (the Klein-Tonelli embedding of
/// `2I ⊂ SU(2)` into `(CP^2)²`).
///
/// Reference: Klein 1884 *Vorlesungen über das Ikosaeder* §I.7;
/// Du Val 1964 *Homographies, Quaternions, and Rotations* §8.
#[inline]
pub fn icosa_z5_character(exps: &[u32; 8]) -> u32 {
    (exps[1] + 2 * exps[2] + exps[4] + 2 * exps[5]) % 5
}

/// H_4-projected (Schoen) basis: monomials with `α = 0`, `β = 0`,
/// and `χ_5 = 0` simultaneously.
///
/// This is the gateway sector — the test-function subspace where the
/// journal §L.1 / §L.2 places the H_4 lepton ground state ω_fix.
pub fn build_h4_projected_basis_schoen(basis: &[TestMonomial]) -> Vec<TestMonomial> {
    basis
        .iter()
        .filter(|m| {
            alpha_character(&m.exponents) == 0
                && beta_character(&m.exponents) == 0
                && icosa_z5_character(&m.exponents) == 0
        })
        .cloned()
        .collect()
}

/// H_4-projected (Tian-Yau) basis: monomials with TY/Z3 α = 0 and
/// `χ_5 = 0`. The `χ_5` formula on the TY ambient
/// `[z_0, z_1, z_2, z_3, w_0, w_1, w_2, w_3]` is
/// `(z[1] + 2 z[2] + w[1] + 2 w[2]) mod 5`, the Z/5 partner of the
/// TY/Z3 α-character.
#[inline]
pub fn icosa_z5_character_ty(exps: &[u32; 8]) -> u32 {
    (exps[1] + 2 * exps[2] + exps[5] + 2 * exps[6]) % 5
}

pub fn build_h4_projected_basis_ty(basis: &[TestMonomial]) -> Vec<TestMonomial> {
    basis
        .iter()
        .filter(|m| ty_z3_character(&m.exponents) == 0 && icosa_z5_character_ty(&m.exponents) == 0)
        .cloned()
        .collect()
}

// ---------------------------------------------------------------------
// Public driver: project basis (Z/3 × Z/3 ∩ icosa-Z/5), run Galerkin.
// ---------------------------------------------------------------------

/// Result type — matches [`crate::route34::metric_laplacian_projected::ProjectedSpectrumReport`]
/// with one extra field for the icosahedral-Z/5 survival fraction.
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct H4ProjectedSpectrumReport {
    /// Standard Galerkin spectrum on the H_4-projected basis.
    pub spectrum: MetricLaplacianSpectrum,
    /// Symmetry projection that was applied (string label).
    pub projection: String,
    /// Original (full) basis dimension before any projection.
    pub full_basis_dim: usize,
    /// After Z/3 × Z/3 (or TY/Z3) trivial-rep filter only.
    pub gamma_projected_basis_dim: usize,
    /// After both the Γ-quotient and icosahedral-Z/5 filter.
    pub h4_projected_basis_dim: usize,
    /// `gamma_projected_basis_dim / full_basis_dim`.
    pub gamma_survival_fraction: f64,
    /// `h4_projected_basis_dim / full_basis_dim`.
    pub h4_survival_fraction: f64,
    /// `h4_projected_basis_dim / gamma_projected_basis_dim` —
    /// fraction of Γ-invariants that are also Z/5-invariant.
    pub h4_relative_survival_fraction: f64,
}

/// Compute the metric-Laplacian spectrum on the
/// `(α, β, χ_5) = (0, 0, 0)` (Schoen) or `(α, χ_5) = (0, 0)` (TY)
/// sub-Coxeter sector — the H_4 lepton sector of the journal
/// §L.1 / §L.2 identification.
pub fn compute_h4_projected_metric_laplacian_spectrum(
    metric: &dyn MetricBackground,
    config: &MetricLaplacianConfig,
    projection: ProjectionKind,
) -> H4ProjectedSpectrumReport {
    let started = Instant::now();
    let full = build_test_basis(config.max_total_degree);
    let full_basis_dim = full.len();

    // Step 1: project to Γ-invariants only (matches the existing
    // Z/3×Z/3 / Z/3 trivial-rep filter for direct comparability with
    // P7.2b).
    let gamma_basis: Vec<TestMonomial> = match projection {
        ProjectionKind::SchoenZ3xZ3 => full
            .iter()
            .filter(|m| alpha_character(&m.exponents) == 0 && beta_character(&m.exponents) == 0)
            .cloned()
            .collect(),
        ProjectionKind::TianYauZ3 => full
            .iter()
            .filter(|m| ty_z3_character(&m.exponents) == 0)
            .cloned()
            .collect(),
    };
    let gamma_dim = gamma_basis.len();

    // Step 2: additionally project on the icosahedral fivefold.
    let h4_basis: Vec<TestMonomial> = match projection {
        ProjectionKind::SchoenZ3xZ3 => gamma_basis
            .iter()
            .filter(|m| icosa_z5_character(&m.exponents) == 0)
            .cloned()
            .collect(),
        ProjectionKind::TianYauZ3 => gamma_basis
            .iter()
            .filter(|m| icosa_z5_character_ty(&m.exponents) == 0)
            .cloned()
            .collect(),
    };
    let n_b = h4_basis.len();
    let n_pts = metric.n_points();

    let proj_label = match projection {
        ProjectionKind::SchoenZ3xZ3 => "schoen_z3xz3_intersect_icosa_z5",
        ProjectionKind::TianYauZ3 => "ty_z3_intersect_icosa_z5",
    };

    let gamma_survival = if full_basis_dim > 0 {
        gamma_dim as f64 / full_basis_dim as f64
    } else {
        0.0
    };
    let h4_survival = if full_basis_dim > 0 {
        n_b as f64 / full_basis_dim as f64
    } else {
        0.0
    };
    let h4_rel_survival = if gamma_dim > 0 {
        n_b as f64 / gamma_dim as f64
    } else {
        0.0
    };

    if n_b == 0 || n_pts == 0 {
        return H4ProjectedSpectrumReport {
            spectrum: MetricLaplacianSpectrum {
                eigenvalues: Vec::new(),
                eigenvalues_full: Vec::new(),
                basis_dim: n_b,
                n_points: n_pts,
                wall_clock_seconds: started.elapsed().as_secs_f64(),
                basis_exponents: None,
                eigenvectors_full: None,
                orthogonalized_basis_dim: 0,
            },
            projection: proj_label.to_string(),
            full_basis_dim,
            gamma_projected_basis_dim: gamma_dim,
            h4_projected_basis_dim: n_b,
            gamma_survival_fraction: gamma_survival,
            h4_survival_fraction: h4_survival,
            h4_relative_survival_fraction: h4_rel_survival,
        };
    }

    let pts = metric.sample_points();

    // Evaluate the H_4-projected basis at every sample point + 8 partials.
    // Layouts mirror metric_laplacian_projected exactly.
    let mut basis_at = vec![Complex64::new(0.0, 0.0); n_b * n_pts];
    let mut d_basis_at = vec![Complex64::new(0.0, 0.0); n_b * 8 * n_pts];
    for alpha in 0..n_b {
        let exps = h4_basis[alpha].exponents;
        for p in 0..n_pts {
            basis_at[alpha * n_pts + p] = eval_monomial(&pts[p], &exps);
        }
        for i in 0..8 {
            let (coeff, dexps) = d_dz(&exps, i);
            if coeff == 0.0 {
                continue;
            }
            let cz = Complex64::new(coeff, 0.0);
            for p in 0..n_pts {
                d_basis_at[(alpha * 8 + i) * n_pts + p] = cz * eval_monomial(&pts[p], &dexps);
            }
        }
    }

    let m_mat = build_mass_matrix(&basis_at, n_b, metric);
    let k_mat = build_stiffness_matrix(&d_basis_at, n_b, metric);

    let m_inv = invert_hermitian_regularised(&m_mat, n_b, config.mass_regularisation);
    let l_eff = matmul_complex(&m_inv, &k_mat, n_b);

    let mut l_h = l_eff;
    for i in 0..n_b {
        let z = l_h[i * n_b + i];
        l_h[i * n_b + i] = Complex64::new(z.re, 0.0);
        for j in (i + 1)..n_b {
            let a = l_h[i * n_b + j];
            let b = l_h[j * n_b + i].conj();
            let avg = (a + b) * 0.5;
            l_h[i * n_b + j] = avg;
            l_h[j * n_b + i] = avg.conj();
        }
    }
    let (eigvals, evecs) =
        hermitian_jacobi_n(&l_h, n_b, config.jacobi_max_sweeps, config.jacobi_tol);

    let mut full_indexed: Vec<(usize, f64)> = eigvals
        .iter()
        .enumerate()
        .map(|(i, &v)| (i, v.abs()))
        .collect();
    full_indexed.sort_by(|a, b| a.1.partial_cmp(&b.1).unwrap_or(std::cmp::Ordering::Equal));
    let full_eigs: Vec<f64> = full_indexed.iter().map(|(_, v)| *v).collect();

    let n_low = config.n_low_eigenvalues.min(full_eigs.len());
    let low: Vec<f64> = full_eigs.iter().take(n_low).cloned().collect();

    let (basis_exponents, eigenvectors_full) = if config.return_eigenvectors {
        let mut sorted_evecs = vec![(0.0_f64, 0.0_f64); n_b * n_b];
        for (new_j, (old_j, _)) in full_indexed.iter().enumerate() {
            for i in 0..n_b {
                let z = evecs[i * n_b + *old_j];
                sorted_evecs[i * n_b + new_j] = (z.re, z.im);
            }
        }
        let exps: Vec<[u32; 8]> = h4_basis.iter().map(|m| m.exponents).collect();
        (Some(exps), Some(sorted_evecs))
    } else {
        (None, None)
    };

    H4ProjectedSpectrumReport {
        spectrum: MetricLaplacianSpectrum {
            eigenvalues: low,
            eigenvalues_full: full_eigs,
            basis_dim: n_b,
            n_points: n_pts,
            wall_clock_seconds: started.elapsed().as_secs_f64(),
            basis_exponents,
            eigenvectors_full,
            orthogonalized_basis_dim: 0,
        },
        projection: proj_label.to_string(),
        full_basis_dim,
        gamma_projected_basis_dim: gamma_dim,
        h4_projected_basis_dim: n_b,
        gamma_survival_fraction: gamma_survival,
        h4_survival_fraction: h4_survival,
        h4_relative_survival_fraction: h4_rel_survival,
    }
}

// ---------------------------------------------------------------------
// Local copies of the Galerkin / linalg helpers (same as
// `metric_laplacian_projected`). Kept self-contained per the
// duplication note in the projected module.
// ---------------------------------------------------------------------

#[inline]
fn eval_monomial(point: &[Complex64; 8], exps: &[u32; 8]) -> Complex64 {
    let mut acc = Complex64::new(1.0, 0.0);
    for k in 0..8 {
        let e = exps[k];
        if e == 0 {
            continue;
        }
        let mut base = point[k];
        let mut ee = e;
        let mut term = Complex64::new(1.0, 0.0);
        while ee > 0 {
            if ee & 1 == 1 {
                term *= base;
            }
            ee >>= 1;
            if ee > 0 {
                base = base * base;
            }
        }
        acc *= term;
    }
    acc
}

#[inline]
fn d_dz(exps: &[u32; 8], k: usize) -> (f64, [u32; 8]) {
    if exps[k] == 0 {
        return (0.0, *exps);
    }
    let mut new_exps = *exps;
    let coeff = new_exps[k] as f64;
    new_exps[k] -= 1;
    (coeff, new_exps)
}

fn build_mass_matrix(
    basis_at: &[Complex64],
    n_b: usize,
    metric: &dyn MetricBackground,
) -> Vec<Complex64> {
    let n_pts = metric.n_points();
    let mut m = vec![Complex64::new(0.0, 0.0); n_b * n_b];
    let mut total_w = 0.0f64;
    for p in 0..n_pts {
        let w = metric.weight(p);
        if !w.is_finite() || w <= 0.0 {
            continue;
        }
        let omega = metric.omega(p);
        if !omega.re.is_finite() || !omega.im.is_finite() {
            continue;
        }
        let pw = Complex64::new(omega.norm_sqr() * w, 0.0);
        for alpha in 0..n_b {
            let sa = basis_at[alpha * n_pts + p];
            if sa.norm_sqr() == 0.0 {
                continue;
            }
            let sa_c = sa.conj();
            for beta in alpha..n_b {
                let sb = basis_at[beta * n_pts + p];
                let inc = sa_c * sb * pw;
                m[alpha * n_b + beta] += inc;
            }
        }
        total_w += w;
    }
    if total_w > 0.0 {
        let inv = 1.0 / total_w;
        for z in m.iter_mut() {
            *z *= Complex64::new(inv, 0.0);
        }
    }
    for i in 0..n_b {
        let z = m[i * n_b + i];
        m[i * n_b + i] = Complex64::new(z.re, 0.0);
        for j in (i + 1)..n_b {
            m[j * n_b + i] = m[i * n_b + j].conj();
        }
    }
    m
}

fn build_stiffness_matrix(
    d_basis_at: &[Complex64],
    n_b: usize,
    metric: &dyn MetricBackground,
) -> Vec<Complex64> {
    let n_pts = metric.n_points();
    let mut k = vec![Complex64::new(0.0, 0.0); n_b * n_b];
    let mut total_w = 0.0f64;
    for p in 0..n_pts {
        let w = metric.weight(p);
        if !w.is_finite() || w <= 0.0 {
            continue;
        }
        let omega = metric.omega(p);
        if !omega.re.is_finite() || !omega.im.is_finite() {
            continue;
        }
        let pw = Complex64::new(omega.norm_sqr() * w, 0.0);
        for i in 0..8 {
            for alpha in 0..n_b {
                let da = d_basis_at[(alpha * 8 + i) * n_pts + p];
                if da.norm_sqr() == 0.0 {
                    continue;
                }
                let da_c = da.conj();
                for beta in alpha..n_b {
                    let db = d_basis_at[(beta * 8 + i) * n_pts + p];
                    if db.norm_sqr() == 0.0 {
                        continue;
                    }
                    let inc = da_c * db * pw;
                    k[alpha * n_b + beta] += inc;
                }
            }
        }
        total_w += w;
    }
    if total_w > 0.0 {
        let inv = 1.0 / total_w;
        for z in k.iter_mut() {
            *z *= Complex64::new(inv, 0.0);
        }
    }
    for i in 0..n_b {
        let z = k[i * n_b + i];
        k[i * n_b + i] = Complex64::new(z.re.max(0.0), 0.0);
        for j in (i + 1)..n_b {
            k[j * n_b + i] = k[i * n_b + j].conj();
        }
    }
    k
}

fn matmul_complex(a: &[Complex64], b: &[Complex64], n: usize) -> Vec<Complex64> {
    let mut out = vec![Complex64::new(0.0, 0.0); n * n];
    for i in 0..n {
        for j in 0..n {
            let mut acc = Complex64::new(0.0, 0.0);
            for k in 0..n {
                acc += a[i * n + k] * b[k * n + j];
            }
            out[i * n + j] = acc;
        }
    }
    out
}

fn invert_hermitian_regularised(h: &[Complex64], n: usize, eps: f64) -> Vec<Complex64> {
    if n == 0 {
        return Vec::new();
    }
    let frob = h.iter().map(|z| z.norm_sqr()).sum::<f64>().sqrt();
    let lambda = (frob * eps).max(1.0e-30);
    let two_n = 2 * n;
    let mut m = vec![Complex64::new(0.0, 0.0); n * two_n];
    for i in 0..n {
        for j in 0..n {
            m[i * two_n + j] = h[i * n + j];
        }
        m[i * two_n + i] += Complex64::new(lambda, 0.0);
        m[i * two_n + (n + i)] = Complex64::new(1.0, 0.0);
    }
    for k in 0..n {
        let mut pivot = k;
        let mut best = m[k * two_n + k].norm();
        for r in (k + 1)..n {
            let v = m[r * two_n + k].norm();
            if v > best {
                best = v;
                pivot = r;
            }
        }
        if best < 1.0e-300 {
            let mut id = vec![Complex64::new(0.0, 0.0); n * n];
            let inv = 1.0 / lambda.max(1.0e-30);
            for i in 0..n {
                id[i * n + i] = Complex64::new(inv, 0.0);
            }
            return id;
        }
        if pivot != k {
            for j in 0..two_n {
                m.swap(k * two_n + j, pivot * two_n + j);
            }
        }
        let pinv = Complex64::new(1.0, 0.0) / m[k * two_n + k];
        for j in 0..two_n {
            m[k * two_n + j] = m[k * two_n + j] * pinv;
        }
        for r in 0..n {
            if r == k {
                continue;
            }
            let factor = m[r * two_n + k];
            if factor.norm() == 0.0 {
                continue;
            }
            for j in 0..two_n {
                let kv = m[k * two_n + j];
                m[r * two_n + j] = m[r * two_n + j] - factor * kv;
            }
        }
    }
    let mut out = vec![Complex64::new(0.0, 0.0); n * n];
    for i in 0..n {
        for j in 0..n {
            out[i * n + j] = m[i * two_n + (n + j)];
        }
    }
    out
}

fn hermitian_jacobi_n(
    a_in: &[Complex64],
    n: usize,
    max_sweeps: usize,
    tol: f64,
) -> (Vec<f64>, Vec<Complex64>) {
    let mut a: Vec<Complex64> = a_in.to_vec();
    let mut v: Vec<Complex64> = vec![Complex64::new(0.0, 0.0); n * n];
    for i in 0..n {
        v[i * n + i] = Complex64::new(1.0, 0.0);
    }
    for _sweep in 0..max_sweeps {
        let mut off = 0.0f64;
        for p in 0..n {
            for q in 0..n {
                if p != q {
                    off += a[p * n + q].norm_sqr();
                }
            }
        }
        if off.sqrt() < tol {
            break;
        }
        for p in 0..(n - 1) {
            for q in (p + 1)..n {
                let apq = a[p * n + q];
                if apq.norm() < tol {
                    continue;
                }
                let app = a[p * n + p].re;
                let aqq = a[q * n + q].re;
                let abs_pq = apq.norm();
                let phi = if abs_pq < 1.0e-300 { 0.0 } else { apq.arg() };
                let theta_arg = if (app - aqq).abs() < 1.0e-300 {
                    std::f64::consts::FRAC_PI_4
                } else {
                    0.5 * (2.0 * abs_pq / (app - aqq)).atan()
                };
                let c = theta_arg.cos();
                let s = theta_arg.sin();
                let cs_phi = Complex64::new(0.0, phi).exp() * Complex64::new(s, 0.0);
                for k in 0..n {
                    let akp = a[k * n + p];
                    let akq = a[k * n + q];
                    a[k * n + p] = akp * Complex64::new(c, 0.0) + akq * cs_phi.conj();
                    a[k * n + q] = akq * Complex64::new(c, 0.0) - akp * cs_phi;
                }
                for k in 0..n {
                    let apk = a[p * n + k];
                    let aqk = a[q * n + k];
                    a[p * n + k] = apk * Complex64::new(c, 0.0) + aqk * cs_phi;
                    a[q * n + k] = aqk * Complex64::new(c, 0.0) - apk * cs_phi.conj();
                }
                a[p * n + q] = Complex64::new(0.0, 0.0);
                a[q * n + p] = Complex64::new(0.0, 0.0);
                a[p * n + p] = Complex64::new(a[p * n + p].re, 0.0);
                a[q * n + q] = Complex64::new(a[q * n + q].re, 0.0);
                for k in 0..n {
                    let vkp = v[k * n + p];
                    let vkq = v[k * n + q];
                    v[k * n + p] = vkp * Complex64::new(c, 0.0) + vkq * cs_phi.conj();
                    v[k * n + q] = vkq * Complex64::new(c, 0.0) - vkp * cs_phi;
                }
            }
        }
    }
    let mut eig: Vec<(usize, f64)> = (0..n).map(|i| (i, a[i * n + i].re)).collect();
    eig.sort_by(|a, b| a.1.partial_cmp(&b.1).unwrap_or(std::cmp::Ordering::Equal));
    let mut eig_sorted = vec![0.0f64; n];
    let mut v_sorted = vec![Complex64::new(0.0, 0.0); n * n];
    for (new_k, (old_k, val)) in eig.iter().enumerate() {
        eig_sorted[new_k] = *val;
        for i in 0..n {
            v_sorted[i * n + new_k] = v[i * n + *old_k];
        }
    }
    (eig_sorted, v_sorted)
}

// ---------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    /// Schoen H_4-projection survives ~1/45 of basis at large degree
    /// (1/9 from Z/3 × Z/3 times 1/5 from icosa-Z/5, modulo finite-
    /// degree edge effects).
    #[test]
    fn schoen_h4_projection_survival_at_d4() {
        let basis = build_test_basis(4);
        let projected = build_h4_projected_basis_schoen(&basis);
        let frac = projected.len() as f64 / basis.len() as f64;
        // Expect 1/45 ≈ 0.022. Allow [0.005, 0.15] given small-degree
        // edge effects.
        assert!(
            (0.005..=0.15).contains(&frac),
            "schoen H_4 projection survival {frac} outside [0.005, 0.15] at d=4 \
             (basis_dim {}, projected {})",
            basis.len(),
            projected.len()
        );
        for m in &projected {
            assert_eq!(alpha_character(&m.exponents), 0);
            assert_eq!(beta_character(&m.exponents), 0);
            assert_eq!(icosa_z5_character(&m.exponents), 0);
        }
    }

    /// Idempotency: reapplying the projector is a no-op.
    #[test]
    fn projector_idempotent_h4_schoen() {
        let basis = build_test_basis(3);
        let p1 = build_h4_projected_basis_schoen(&basis);
        let p2 = build_h4_projected_basis_schoen(&p1);
        assert_eq!(p1.len(), p2.len());
        for (a, b) in p1.iter().zip(p2.iter()) {
            assert_eq!(a.exponents, b.exponents);
        }
    }

    /// `χ_5` and `α` characters disagree on a generic monomial: the
    /// fivefold projection is independent of the threefold.
    #[test]
    fn icosa_z5_character_distinct_from_alpha() {
        // x_1^2 has α = 2 (mod 3) and χ_5 = 2 (mod 5); these happen
        // to coincide as integers but the moduli differ.
        let exps = [0u32, 2, 0, 0, 0, 0, 0, 0];
        assert_eq!(alpha_character(&exps), 2);
        assert_eq!(icosa_z5_character(&exps), 2);
        // x_1^3 has α = 0 (Γ-invariant) but χ_5 = 3 (NOT H_4-invariant).
        let exps = [0u32, 3, 0, 0, 0, 0, 0, 0];
        assert_eq!(alpha_character(&exps), 0);
        assert_eq!(icosa_z5_character(&exps), 3);
        // x_1^5 has α = 2 (NOT Γ-invariant) but χ_5 = 0 (Z/5-invariant).
        let exps = [0u32, 5, 0, 0, 0, 0, 0, 0];
        assert_eq!(alpha_character(&exps), 2);
        assert_eq!(icosa_z5_character(&exps), 0);
        // x_1^15 has both α = 0 and χ_5 = 0 — fully H_4-invariant.
        let exps = [0u32, 15, 0, 0, 0, 0, 0, 0];
        assert_eq!(alpha_character(&exps), 0);
        assert_eq!(icosa_z5_character(&exps), 0);
    }
}
