//! # Structured `E_8` Wilson-line element
//!
//! For a CY3 `M̃` with a freely-acting discrete group `Γ` (here
//! `Z/3` for Tian-Yau or `Z/3 × Z/3` for Schoen), and a heterotic
//! gauge bundle of structure group `H ⊂ E_8`, the **Wilson line**
//! `W ∈ E_8` is a flat connection on the quotient `M = M̃ / Γ`
//! satisfying
//!
//! ```text
//!     W^{|Γ|} = 1   in   E_8.
//! ```
//!
//! Concretely `W = exp(2π i α / N)` for an element `α` of the
//! `E_8` Cartan subalgebra `t ⊂ e_8` such that `N · α` lies in
//! the `E_8` root lattice `Λ_root`. Different orbits `α + Λ_root`
//! give physically distinct unbroken subgroups under the Wilson-
//! line breaking
//!
//! ```text
//!     E_8  →  Comm(W, E_8)  ⊂  E_8.
//! ```
//!
//! Anderson-Gray-Lukas-Palti 2011 (arXiv:1106.4804) and Braun-He-
//! Ovrut-Pantev 2005 (arXiv:hep-th/0501070) commit to the
//! `E_8 → E_6 × SU(3)` decomposition via a specific `Z/3` Wilson
//! line — the one whose `α` is the third fundamental coweight of
//! the `SU(3)` factor in the `SU(3) × E_6 ⊂ E_8` maximal
//! subalgebra. This module implements that mathematical embedding
//! using the canonical `E_8` simple-root basis (Bourbaki *Lie
//! Groups and Lie Algebras* Ch. VI §4, Plate VII; Slansky 1981
//! *Phys. Rep.* **79** §6).
//!
//! ## Canonical `E_8` simple roots
//!
//! In the standard `R^8` realization (Bourbaki Plate VII), the
//! eight simple roots `α_1, …, α_8` of `E_8` are
//!
//! ```text
//!     α_1 = (1/2)(1, -1, -1, -1, -1, -1, -1, 1)
//!     α_2 = (1, 1, 0, 0, 0, 0, 0, 0)
//!     α_3 = (-1, 1, 0, 0, 0, 0, 0, 0)
//!     α_4 = (0, -1, 1, 0, 0, 0, 0, 0)
//!     α_5 = (0, 0, -1, 1, 0, 0, 0, 0)
//!     α_6 = (0, 0, 0, -1, 1, 0, 0, 0)
//!     α_7 = (0, 0, 0, 0, -1, 1, 0, 0)
//!     α_8 = (0, 0, 0, 0, 0, -1, 1, 0)
//! ```
//!
//! (Bourbaki labels them differently; the labelling here is the
//! Slansky 1981 ordering used in particle physics.)
//! The fundamental coweights `ω_i^∨` are dual to `α_i` under the
//! pairing `⟨ω_j^∨, α_i⟩ = δ_{ij}`. In our `R^8` realization the
//! coweights are computed by inverting the Cartan matrix.
//!
//! ## `E_8 → E_6 × SU(3)` Wilson line
//!
//! The maximal subalgebra `e_6 + su(3) ⊂ e_8` has its `SU(3)`
//! factor generated by the simple roots `α_1, α_2` and their
//! associated negative roots, with `e_6` generated by
//! `α_3, α_4, α_5, α_6, α_7, α_8`. The Wilson line that breaks
//! `E_8 → E_6 × SU(3)` is `W = exp(2π i ω_2^∨ / 3)`, where
//! `ω_2^∨` is the second fundamental coweight (in the Slansky
//! labelling). Explicitly,
//!
//! ```text
//!     ω_2^∨ = (1/3)(0, 0, 0, 0, 0, 0, -2, 2)        (Slansky 1981 Table 16)
//! ```
//!
//! and `3 · ω_2^∨ = (0, 0, 0, 0, 0, 0, -2, 2)` lies in the root
//! lattice (it equals `α_8 + …`). The Wilson line angle is
//!
//! ```text
//!     α_W := ω_2^∨ / 3 · 2π   →   cartan_phases = ω_2^∨
//! ```
//!
//! interpreted as the 8-vector multiplied by the implicit `2π/3`.
//! Our [`WilsonLineE8::canonical_e8_to_e6_su3`] returns this
//! canonical element.
//!
//! ## Unbroken subalgebra
//!
//! The unbroken subalgebra is the centraliser of `W` in `e_8`,
//! generated by the Cartan plus all roots `β` with
//! `⟨β, α_W⟩ ∈ Z`. For the canonical `α_W = ω_2^∨ / 3`, the
//! invariant roots are exactly those of `e_6 + su(3)`.
//!
//! ## References
//!
//! * Bourbaki, *Lie Groups and Lie Algebras*, Ch. IV–VI (Springer 2002),
//!   Plate VII (`E_8` simple roots and Cartan matrix).
//! * Slansky, "Group Theory for Unified Model Building",
//!   *Phys. Rep.* **79** (1981) 1–128, §6 and Table 16.
//! * Anderson, Gray, Lukas, Palti, JHEP **06** (2012) 113,
//!   arXiv:1106.4804.
//! * Braun, He, Ovrut, Pantev, *Phys. Lett. B* **618** (2005)
//!   252, arXiv:hep-th/0501070.

use std::f64::consts::PI;

use serde::{Deserialize, Serialize};

use crate::route34::bundle_search::LineBundleDegrees;

// ----------------------------------------------------------------------
// Canonical E_8 root system.
// ----------------------------------------------------------------------

/// The `E_8` simple roots in the canonical `R^8` realization
/// (Bourbaki Plate VII, Slansky 1981 Table 16). Order is the
/// physics-convention "α_1 = spinor root" Slansky labelling.
///
/// Each row is the 8-component coefficient of one simple root.
pub const E8_SIMPLE_ROOTS: [[f64; 8]; 8] = [
    [0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5, 0.5],
    [1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    [-1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    [0.0, -1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    [0.0, 0.0, -1.0, 1.0, 0.0, 0.0, 0.0, 0.0],
    [0.0, 0.0, 0.0, -1.0, 1.0, 0.0, 0.0, 0.0],
    [0.0, 0.0, 0.0, 0.0, -1.0, 1.0, 0.0, 0.0],
    [0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 1.0, 0.0],
];

/// Generate all 240 roots of `E_8`. Two families:
///
/// * **D_8 part**: `±e_i ± e_j` for `1 ≤ i < j ≤ 8` (any sign
///   choice). Cardinality: `4 · C(8, 2) = 112`.
/// * **Half-integer spinor part**: `(±1/2, ±1/2, …, ±1/2)` with
///   an even number of `−1/2` signs. Cardinality: `2^7 = 128`.
///
/// Reference: Bourbaki Plate VII; Conway-Sloane *Sphere Packings,
/// Lattices and Groups* (Springer 1999, 3rd ed.) Ch. 4 §8.1.
///
/// Cardinality check: `112 + 128 = 240`, the dimension count of
/// `e_8 / t_8`.
pub fn e8_roots() -> Vec<[f64; 8]> {
    let mut roots: Vec<[f64; 8]> = Vec::with_capacity(240);
    // D_8 roots: ±e_i ± e_j, i < j.
    for i in 0..8 {
        for j in (i + 1)..8 {
            for s_i in [1.0_f64, -1.0] {
                for s_j in [1.0_f64, -1.0] {
                    let mut r = [0.0; 8];
                    r[i] = s_i;
                    r[j] = s_j;
                    roots.push(r);
                }
            }
        }
    }
    // Spinor roots: (±1/2)^8 with even number of minuses.
    for mask in 0u32..(1 << 8) {
        if (mask.count_ones() % 2) != 0 {
            continue;
        }
        let mut r = [0.0; 8];
        for k in 0..8 {
            r[k] = if (mask >> k) & 1 == 1 { -0.5 } else { 0.5 };
        }
        roots.push(r);
    }
    debug_assert_eq!(roots.len(), 240, "E_8 must have exactly 240 roots");
    roots
}

/// The `E_8` root lattice consists of integer linear combinations
/// of simple roots; equivalently, vectors `v ∈ R^8` with all
/// integer coordinates and even coordinate sum, plus all
/// half-integer-coordinate vectors with sum integer.
///
/// Returns `true` iff `v` lies in `Λ_root(E_8)`.
pub fn in_e8_root_lattice(v: &[f64; 8]) -> bool {
    // Two cases: all integer coords with even sum, or all
    // half-integer coords (offset by 1/2) with integer sum.
    // We check up to a small tolerance so that floating-point
    // drift in `3 · α` doesn't reject genuine lattice points.
    let eps = 1.0e-9;
    let near_int = |x: f64| (x - x.round()).abs() < eps;
    let near_half = |x: f64| ((x - x.round()).abs() - 0.5).abs() < eps;

    let all_int = v.iter().all(|&x| near_int(x));
    let all_half = v.iter().all(|&x| near_half(x));
    if all_int {
        let s: f64 = v.iter().map(|&x| x.round()).sum();
        return (s.round() as i64) % 2 == 0;
    }
    if all_half {
        // Each coord = k + 1/2 for integer k. Sum = Σ k + 8·(1/2)
        //   = Σ k + 4. The sum is integer ⇔ Σ k integer (always).
        // The Z-condition for the spinor sublattice is that the
        // number of (-1/2 + integer) vs (+1/2 + integer)
        // half-coords is congruent (mod 2) to the parity required
        // by the lattice — for E_8 we require sum integer (always
        // satisfied here) AND half-int coords have even number of
        // minus signs. After shifting to half-int representatives
        // {±1/2}, count negatives.
        let mut neg_count = 0u32;
        for &x in v.iter() {
            // Map x = k ± 1/2 into the {±1/2} representative
            // by reducing modulo 1.
            let r = x - x.floor();
            // r is in [0, 1). If r > 0.5 we round up: was +1/2.
            if r < 0.5 {
                neg_count += 1;
            }
        }
        return neg_count % 2 == 0;
    }
    false
}

// ----------------------------------------------------------------------
// WilsonLineE8: structured Wilson-line element.
// ----------------------------------------------------------------------

/// Structured `E_8` Wilson-line element for `Z/N` quotient.
///
/// `cartan_phases` stores the 8-vector `α ∈ t ⊂ e_8` (real).
/// The Wilson-line element itself is `W = exp(2π i α / N)` for
/// `N = quotient_order`. The integrality condition `W^N = 1` is
/// `N · α ∈ Λ_root(E_8)`, checked exactly via
/// [`Self::quantization_residual`].
#[derive(Clone, Copy, Debug, PartialEq, Serialize, Deserialize)]
pub struct WilsonLineE8 {
    /// 8-component vector `α` in the `R^8` Cartan realisation.
    pub cartan_phases: [f64; 8],
    /// Order `N = |Γ|` of the discrete group whose quotient
    /// supports this Wilson line. `N = 3` for Tian-Yau (`Z/3`),
    /// `N = 9` for Schoen (`Z/3 × Z/3`).
    pub quotient_order: u32,
}

impl Eq for WilsonLineE8 {}

impl WilsonLineE8 {
    /// Construct directly from `cartan_phases` and `quotient_order`.
    pub fn new(cartan_phases: [f64; 8], quotient_order: u32) -> Self {
        Self {
            cartan_phases,
            quotient_order: quotient_order.max(1),
        }
    }

    /// The canonical Wilson line for `E_8 → E_6 × SU(3)`.
    ///
    /// In the orthonormal `R^8` realisation of `E_8` (Bourbaki
    /// Plate VII), the maximal subalgebra `e_6 + su(3) ⊂ e_8`
    /// is the centraliser of the third-fundamental-coweight
    /// element. One Slansky-1981-Table-23 representative with
    /// `1/3`-spaced entries is
    ///
    /// ```text
    ///     α = (1/3) · (2, -1, -1, 0, 0, 0, 0, 0).
    /// ```
    ///
    /// Verification of the unbroken subalgebra (matches Slansky):
    ///
    /// * `D_8` roots `±e_i ± e_j` with `i, j ∈ {3, …, 7}`: 40
    ///   invariant.
    /// * `D_8` roots `±(e_0 - e_1)`, `±(e_0 - e_2)`, `±(e_1 - e_2)`:
    ///   6 invariant.
    /// * Spinor `(±1/2)^8` with `(s_0, s_1, s_2) ∈ {(+,+,+), (-,-,-)}`
    ///   times the parity-even count over the remaining 5
    ///   half-coords: `2 · 2^4 = 32` invariant.
    ///
    /// Total invariant roots: `40 + 6 + 32 = 78 = #roots(E_6) +
    /// #roots(SU(3)) = 72 + 6`. (`dim E_6 = 78` is the LIE-ALGEBRA
    /// dimension `#roots + rank = 72 + 6`, NOT the root count;
    /// `dim SU(3) = 8 = #roots + rank = 6 + 2`. The previous wording
    /// here conflated `#roots(E_6)` with `dim E_6` and was incorrect.)
    /// The Wilson line leaves `dim(E_6 × SU(3)) = (72 + 6) + (6 + 2)
    /// = 86` generators invariant: 78 root-generators plus 8 Cartan
    /// generators. Reference: Bourbaki, *Lie Groups and Lie Algebras*
    /// Plate VII (E_6 has 72 roots / Lie-dim 78); Slansky 1981
    /// *Phys. Rep.* **79** Tab. 23 (E_6 × SU(3) decomposition of E_8).
    ///
    /// `3 · α = (2, -1, -1, 0, 0, 0, 0, 0)` lies in the `D_8`
    /// sublattice of `Λ_root(E_8)` (integer entries with even
    /// sum), so `W^3 = 1` exactly.
    ///
    /// For `Z/3 × Z/3` (Schoen) the same `α` provides one of the
    /// two `Z/3` Wilson factors; the second factor (along an
    /// independent `SU(3)`-Cartan direction) is folded into the
    /// `quotient_order = 9` quantum, and the integer-vector
    /// `9 · α = (6, -3, -3, 0, …, 0)` stays in the lattice.
    pub fn canonical_e8_to_e6_su3(quotient_order: u32) -> Self {
        let cartan_phases = [
            2.0 / 3.0,
            -1.0 / 3.0,
            -1.0 / 3.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
        ];
        Self {
            cartan_phases,
            quotient_order: quotient_order.max(1),
        }
    }

    /// `Z/N` quantization residual: distance from `N · α` to the
    /// nearest point of the `E_8` root lattice. Zero iff
    /// `W^N = 1` exactly.
    ///
    /// We use a coarse "closest-lattice-point" surrogate: round
    /// `N · α` to the nearest E_8-lattice candidate (snap to the
    /// integer-coord vector with even sum, or the half-integer-
    /// coord vector with integer sum, whichever is nearer) and
    /// return the squared L^2 distance.
    pub fn quantization_residual(&self) -> f64 {
        let n = self.quotient_order as f64;
        let scaled: [f64; 8] = [
            n * self.cartan_phases[0],
            n * self.cartan_phases[1],
            n * self.cartan_phases[2],
            n * self.cartan_phases[3],
            n * self.cartan_phases[4],
            n * self.cartan_phases[5],
            n * self.cartan_phases[6],
            n * self.cartan_phases[7],
        ];

        // Distance to integer lattice with even sum.
        let int_round: [f64; 8] = [
            scaled[0].round(),
            scaled[1].round(),
            scaled[2].round(),
            scaled[3].round(),
            scaled[4].round(),
            scaled[5].round(),
            scaled[6].round(),
            scaled[7].round(),
        ];
        let int_sum: f64 = int_round.iter().sum::<f64>();
        let parity = (int_sum.round() as i64).rem_euclid(2);
        let mut int_target = int_round;
        if parity != 0 {
            // Flip the rounding on the entry with smallest |frac|
            // so that the parity becomes even.
            let mut k_flip = 0;
            let mut best = f64::INFINITY;
            for k in 0..8 {
                let f = (scaled[k] - int_round[k]).abs();
                if f < best {
                    best = f;
                    k_flip = k;
                }
            }
            // Flip up or down depending on the sign of the residual.
            if scaled[k_flip] - int_round[k_flip] >= 0.0 {
                int_target[k_flip] += 1.0;
            } else {
                int_target[k_flip] -= 1.0;
            }
        }
        let int_dist_sq: f64 = (0..8)
            .map(|k| {
                let d = scaled[k] - int_target[k];
                d * d
            })
            .sum();

        // Distance to half-integer lattice (Spin sublattice with
        // even number of −1/2 signs).
        let half_target: [f64; 8] = (0..8)
            .map(|k| {
                let r = (scaled[k] - 0.5).round() + 0.5;
                r
            })
            .collect::<Vec<_>>()
            .try_into()
            .expect("half-int target builds");
        // Enforce even-minus-count convention: half-integers
        // representing −1/2 (mod 1) need an even count.
        let mut half_with_parity = half_target;
        let mut neg_count: u32 = 0;
        for &x in &half_with_parity {
            // x = k + 1/2 for some integer k. We treat "below 0"
            // as a negative spinor coord.
            let r = x - x.floor();
            if r < 0.5 - 1.0e-9 {
                neg_count += 1;
            }
        }
        if neg_count % 2 != 0 {
            // Flip the entry with smallest absolute deviation.
            let mut k_flip = 0;
            let mut best = f64::INFINITY;
            for k in 0..8 {
                let f = (scaled[k] - half_target[k]).abs();
                if f < best {
                    best = f;
                    k_flip = k;
                }
            }
            // Flip half-integer to the next half-integer.
            if scaled[k_flip] - half_target[k_flip] >= 0.0 {
                half_with_parity[k_flip] += 1.0;
            } else {
                half_with_parity[k_flip] -= 1.0;
            }
        }
        let half_dist_sq: f64 = (0..8)
            .map(|k| {
                let d = scaled[k] - half_with_parity[k];
                d * d
            })
            .sum();

        int_dist_sq.min(half_dist_sq)
    }

    /// Compute the unbroken subgroup of `E_8` under conjugation
    /// by `W = exp(2π i α / N)`. The unbroken subalgebra is
    /// generated by the Cartan plus all roots `β` of `E_8`
    /// satisfying `⟨β, α⟩ ∈ Z` (the integrality condition for
    /// `W` to commute with the corresponding root vector).
    pub fn unbroken_subalgebra(&self) -> UnbrokenSubgroup {
        let mut count = 0;
        for r in e8_roots() {
            let mut ip = 0.0;
            for k in 0..8 {
                ip += r[k] * self.cartan_phases[k];
            }
            if (ip - ip.round()).abs() < 1.0e-9 {
                count += 1;
            }
        }
        // For canonical `E_8 → E_6 × SU(3)`, the count is
        // dim(E_6) - rank(E_6) + dim(SU(3)) - rank(SU(3))
        //   = (78 - 6) + (8 - 2) = 72 + 6 = 78 roots.
        // (E_6 has 72 roots, SU(3) has 6 roots.)
        // Plus the 8 Cartan generators on top, for total
        // dim(H) = 78 + 8 = 86 = 78(E_6) + 8(SU(3)).
        UnbrokenSubgroup {
            invariant_root_count: count,
            cartan_dim: 8,
        }
    }

    /// True iff this Wilson line:
    /// (a) is `Z/|Γ|`-quantized (`quantization_residual` zero), AND
    /// (b) leaves `E_6 × SU(3)` exactly unbroken (78 invariant
    ///     roots, total Lie dimension 86), AND
    /// (c) the bundle has `c_1 = 0` (the SU(n) condition required
    ///     for the bundle's structure group to embed into the
    ///     `SU(3)` commutant of `E_6` inside `E_8`).
    pub fn embeds_for_se(&self, bundle: &LineBundleDegrees) -> bool {
        if self.quantization_residual() > 1.0e-7 {
            return false;
        }
        let unbroken = self.unbroken_subalgebra();
        if !unbroken.is_e6_times_su3() {
            return false;
        }
        // Bundle must be SU(n): c_1 = 0 and rank ≥ 1.
        let rank = bundle.rank();
        if rank < 1 {
            return false;
        }
        if bundle.derived_chern().c1 != 0 {
            return false;
        }
        true
    }
}

// ----------------------------------------------------------------------
// UnbrokenSubgroup: result type for Wilson-line breaking analysis.
// ----------------------------------------------------------------------

/// The unbroken subalgebra of `e_8` after Wilson-line breaking.
///
/// `invariant_root_count` is the number of `e_8` roots `β` such
/// that `⟨β, α⟩ ∈ Z`; together with the rank-8 Cartan, the total
/// dimension of the unbroken subalgebra is
/// `cartan_dim + invariant_root_count`.
///
/// For `E_8 → E_6 × SU(3)` this should be `8 + 78 = 86`.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct UnbrokenSubgroup {
    pub invariant_root_count: usize,
    pub cartan_dim: usize,
}

impl UnbrokenSubgroup {
    /// Total Lie-algebra dimension `dim(h) = rank + #roots`.
    pub fn lie_dimension(&self) -> usize {
        self.cartan_dim + self.invariant_root_count
    }

    /// True iff the unbroken subalgebra has the dimension of
    /// `E_6 × SU(3)`: `78 + 8 = 86`.
    pub fn is_e6_times_su3(&self) -> bool {
        self.lie_dimension() == 86
    }

    /// True iff the unbroken subalgebra is all of `E_8` (no
    /// breaking — the Wilson line is in the centre, mod root
    /// lattice). Then `invariant_root_count = 240` and
    /// `lie_dimension() = 248 = dim E_8`.
    pub fn is_full_e8(&self) -> bool {
        self.invariant_root_count == 240
    }
}

// ----------------------------------------------------------------------
// Convenience: 2π / N reduction of a phase.
// ----------------------------------------------------------------------

/// Reduce a phase `φ` modulo `2π / N`. Used by legacy code that
/// stored Wilson phases as `(2π / N)`-multiples in `bundle_moduli`.
pub fn reduce_phase_mod_quantum(phi: f64, n: u32) -> f64 {
    let q = 2.0 * PI / n as f64;
    phi.rem_euclid(q)
}

#[cfg(test)]
mod unit_tests {
    use super::*;

    #[test]
    fn e8_root_count_matches_dim_minus_rank() {
        let roots = e8_roots();
        assert_eq!(roots.len(), 240, "dim E_8 - rank E_8 = 248 - 8 = 240");
    }

    #[test]
    fn d8_part_count() {
        // ±e_i ± e_j with i < j: 4 · C(8,2) = 4·28 = 112.
        let roots = e8_roots();
        let d8: Vec<_> = roots
            .iter()
            .filter(|r| r.iter().all(|&x| (x - x.round()).abs() < 1.0e-9))
            .collect();
        assert_eq!(d8.len(), 112);
    }

    #[test]
    fn spinor_part_count() {
        // (±1/2)^8 with even number of minuses: 2^7 = 128.
        let roots = e8_roots();
        let spinor: Vec<_> = roots
            .iter()
            .filter(|r| r.iter().all(|&x| (x.abs() - 0.5).abs() < 1.0e-9))
            .collect();
        assert_eq!(spinor.len(), 128);
    }

    #[test]
    fn root_norm_two() {
        // All E_8 roots have norm² = 2 in the standard normalisation.
        for r in e8_roots() {
            let n2: f64 = r.iter().map(|&x| x * x).sum();
            assert!(
                (n2 - 2.0).abs() < 1.0e-9,
                "root norm² should be 2, got {n2} for {r:?}"
            );
        }
    }

    #[test]
    fn canonical_wilson_line_quantization_zero() {
        let w = WilsonLineE8::canonical_e8_to_e6_su3(3);
        let q = w.quantization_residual();
        assert!(
            q < 1.0e-9,
            "canonical Z/3 Wilson line should have quantization_residual = 0, got {q}"
        );
    }

    #[test]
    fn canonical_wilson_line_unbroken_dim_86() {
        let w = WilsonLineE8::canonical_e8_to_e6_su3(3);
        let h = w.unbroken_subalgebra();
        // Slansky-1981 Table 23: canonical α leaves E_6 × SU(3),
        // dim 78 + 8 = 86.
        assert_eq!(h.lie_dimension(), 86);
        assert!(h.is_e6_times_su3());
    }

    #[test]
    fn zero_wilson_line_leaves_full_e8() {
        let w = WilsonLineE8::new([0.0; 8], 3);
        let h = w.unbroken_subalgebra();
        assert!(h.is_full_e8(), "α = 0 ⇒ no breaking");
    }

    #[test]
    fn root_lattice_membership() {
        // (1, -1, 0, 0, 0, 0, 0, 0) is a D_8 root, so in Λ_root.
        let v = [1.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0];
        assert!(in_e8_root_lattice(&v));
        // (1, 0, ..., 0) has odd integer sum ⇒ not in lattice.
        let v = [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0];
        assert!(!in_e8_root_lattice(&v));
        // Spinor root: (1/2)^8 has even number of −1/2 signs (zero).
        let v = [0.5; 8];
        assert!(in_e8_root_lattice(&v));
    }
}
